Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2024
Var
nomedeguerra: vetor[1..3] de caractere
i: inteiro
Inicio
nomedeguerra[1] <- "ivan"
nomedeguerra[2] <- "araujo"
nomedeguerra[3] <- "silva"

para i de 1 ate 3 faca
        escreva(nomedeguerra[i], " ")
fimpara

Fimalgoritmo